## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [27]:
import pandas as pd
#1-1
data_frame = pd.DataFrame(data)
#1-2
data_frame.job.unique()
#1-3
for i, j in data_frame.iterrows():
  if j['job']=='teacher' or j['job']=='psychologist':
    if j['num_cars']>j['family_size']:
      print(j)
#1-4
for i, j in data_frame.iterrows():
  if j['family_size']<=2 and j['num_cars']>=1:
    print(j)

name                   Lisa
job            psychologist
family_size               3
num_cars                  4
Name: 5, dtype: object
name                  Jacob
job            psychologist
family_size               2
num_cars                  1
Name: 1, dtype: object
name                      Sam
job            data scientist
family_size                 1
num_cars                    1
Name: 2, dtype: object
name                   Ryan
job            psychologist
family_size               2
num_cars                  2
Name: 4, dtype: object
name               Lee
job            teacher
family_size          2
num_cars             1
Name: 6, dtype: object


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import numpy as np
import pandas as pd

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
fruit_df = pd.DataFrame({'fruit':fruit,'weights':weights})  
fruit_df

unique_fruit = fruit_df['fruit'].unique()   
mean_weights = list()
for fruits in unique_fruit:   
    mean_weights.append(sum(fruit_df[fruit_df['fruit'] == fruits]['weights']))
    

mean_weights_df = pd.DataFrame({'fruits':unique_fruit,'mean_weights':mean_weights})
mean_weights_df


fruits  mean_weights
0  banana          13.0
1   apple          21.0
2  carrot          21.0

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])
print("Array course name:")
print(course_name)
print("Checking whether each name starts with P")
ch = np.char.startswith(course_name, "P")
print(ch)

Array course name:
['Python' 'JS' 'examples' 'PHP' 'html']
Checking whether each name starts with P
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
# Question 4-1
rev = student_id[::-1]
print("Original Array: "+ str(student_id))
print("Reversed Array: "+ str(rev))
# 4-2
sorted_indices = np.argsort(student_id)
sorted_array = student_id[sorted_indices]
print("3 largest values of student_id array: " + str(sorted_array[-3:]))



Original Array: [1023 5202 6230 1671 1682 5241 4532]
Reversed Array: [4532 5241 1682 1671 6230 5202 1023]
3 largest values of student_id array: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
import numpy as np
x = np.arange(1,100)
n = x[(x % 3 == 0) | (x % 5 == 0)]
print("Sum of all multiples of 3 or 5 below 100: " + str(n.sum()))

Sum of all multiples of 3 or 5 below 100: 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)
# Swap column 1 with column 2
arr[:, [2, 1]] = arr[:, [1, 2]]
print("After Swapping\n")
print(arr)

# 6-2
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

# Swap row 0 with row 1
temp = arr[0,:].copy()
arr[0,:] = arr[1,:]
arr[1,:] = temp
print("After Swapping\n")
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Swapping

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Swapping

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
